name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: "adopt"
    - name: Make Gradle wrapper executable
      run: chmod +x gradlew
    - name: Build with Gradle
      id: gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Store build result
      env:
        BUILD_RESULT: ${{ steps.gradle.outputs.build-result }}
      run: echo "BUILD_RESULT=${BUILD_RESULT}" >> $GITHUB_ENV


