name: build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # 지정한 저장소(현재 REPO)에서 코드를 워크플로우 환경으로 가져오도록 하는 github action
      - uses: actions/checkout@v3

      # open jdk 17 버전 환경을 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "adopt"

      # Github secrets로부터 데이터를 받아서, 워크 플로우에 파일을 생성
      - name: Make application.properties
        run: |
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.PROPERTIES }}" > ./application.properties
        shell: bash

      # gradle을 통해 소스를 빌드.
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

  deploy-to-Server:
    if: github.event_name == 'push'
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checking your input
        run: |
          echo "github.event.pull_request.merged           : $MERGED_RAW"
          echo "github.event.pull_request.merged == 'true' : $MERGED_TRUE_STR"
          echo "github.event.pull_request.merged  == true  : $MERGED_TRUE_BOOL"
        env:
          MERGED_RAW: ${{ github.event.pull_request.merged }}
          MERGED_TRUE_STR: ${{ github.event.pull_request.merged == 'true' }}
          MERGED_TRUE_BOOL: ${{ github.event.pull_request.merged == true }}

#      - uses: actions/checkout@v3

#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: "adopt"

#      - name: make application.properties
#        run: |
#          cd ./src/main/resources
#          touch ./application.properties
#          echo "${{ secrets.PROPERTIES_DEV }}" > ./application.properties
#        shell: bash
#
#      - name: Build with Gradle
#        run: |
#          chmod +x ./gradlew
#          ./gradlew clean build -x test

#      - name: Docker build & push to prod
#        run: |
#          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/springboot-github-actions-test .
#          docker push ${{ secrets.DOCKER_REPO }}/springboot-github-actions-test
#
#      - name: Deploy to Server
#        uses: appleboy/ssh-action@master
#        id: deploy
#        with:
#          host: ${{ secrets.HOST }}
#          username: directors-dev
#          key: ${{ secrets.KEY }}
#          envs: GITHUB_SHA
#          script: |
#            sudo docker rm -f $(docker ps -qa)
#            sudo docker pull ${{ secrets.DOCKER_REPO }}/springboot-github-actions-test
#            docker-compose up -d
#            docker image prune -f